version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    install:
      - pip install -r module_4/requirements.txt

sphinx:
  configuration: module_4/docs/source/conf.py

# Optionally enable other formats (pdf, epub) if needed
# formats:
#   - pdf
#   - epub
