name: Module 4 Tests

on:
  push:
    paths:
      - 'module_4/**'
  pull_request:
    paths:
      - 'module_4/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gradcafe
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gradcafe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: module_4
        run: |
          python -m pip install --upgrade pip
          pip install -r module_4/requirements.txt

      - name: Run pytest
        working-directory: module_4
        run: pytest
